name: tmdpolicy
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - ffmpeg
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu128
      - torch==2.11.0
      - torchvision==0.26.0
      - lerobot[training,pi,smolvla,libero,evaluation]==0.6.1
      - -e ..
